### ISSUE TITLE
Failing install/download requiring user-agent

### ISSUE THREAD

**Issue by johnmorrell** [aerys/gpm#6] opened 2020-10-22 09:01 UTC
Built on: macOS (10.15.7)

When attempting to download or install, I get the following error:

``
ERROR gpm                        > GPM command error: Git LFS error
 ERROR gpm                        > caused by: LFS server error 403 Forbidden: 
Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.
``

This is resolved by adding:

`.header(header::USER_AGENT, "gpm")`

Along with the two `AUTHORIZATION` headers in `lib.rs`

**Comment by JMLX42** [comment] 2020-10-22 12:18
@johnmorrell thank you for reporting this and suggesting a fix.

Could you please share:

- The exact command line used to reproduce the problem.
- The complete stdout/stderr logs.

**Comment by johnmorrell** [comment] 2020-10-22 12:36
```
gpm install ssh://github.com/[redacted]/[redacted].git#[redacted]/0.1.15
 DEBUG gpm::gpm::command::install > parsed package: Package { remote: Some("ssh://github.com/[redacted]/[redacted].git"), name: "[redacted]/0.1.15", version: PackageVersion { raw: "", version_req: None, latest: true } }
 INFO  gpm::gpm::command::install > running the "install" command for package [redacted]/0.1.15 at revision 
Installing package [redacted]/0.1.15
[1/3] Resolving package
 DEBUG gpm::gpm::git              > use existing repository already in cache /Users/[redacted]/.gpm/cache/35946be75ac90e769669021ee8d82335d6f5f9d88bad5e8496f35cb487fe8db4
 INFO  gpm::gpm::git              > fetching changes for repository /Users/[redacted]/.gpm/cache/35946be75ac90e769669021ee8d82335d6f5f9d88bad5e8496f35cb487fe8db4/
 TRACE gpm::gpm::git              > setup git credentials callback
 TRACE gpm::gpm::git              > reset master to HEAD
 TRACE gpm::gpm::git              > checkout head
 DEBUG gpm::gpm::git              > reset head to master
 TRACE gpm::gpm::git              > entering git credentials callback
 DEBUG gpm::gpm::git              > using username from URI
 TRACE gpm::gpm::git              > entering git credentials callback
 DEBUG gpm::gpm::git              > using SSH key
 WARN  gpm::gpm::ssh              > could not read the GPM_SSH_KEY environment variable: environment variable not found
 WARN  gpm::gpm::ssh              > Unable to get SSH key from ~/.ssh/config: IO error
 DEBUG gpm::gpm::ssh              > authenticate with private key located in "/Users/[redacted]/.ssh/id_rsa"
 DEBUG gpm::gpm::git              > fetched changes
 ERROR gpm                        > GPM command error: no matching version for package [redacted]/0.1.15
[redacted]@MacBook-Pro packages % GPM_LOG="gpm=trace,gitlfs=trace" gpm install [redacted]                                            
 DEBUG gpm::gpm::command::install > parsed package: Package { remote: None, name: "[redacted]", version: PackageVersion { raw: "", version_req: None, latest: true } }
 INFO  gpm::gpm::command::install > running the "install" command for package [redacted] at revision 
Installing package [redacted]
[1/3] Resolving package
 DEBUG gpm::gpm::git              > no specific remote provided: searching
  [00:00:00] (0/1) 
 DEBUG gpm::gpm::git              > searching in repository ssh://github.com/[redacted]/packages.git
  [00:00:00] (1/1) ssh://github.com/[redacted]/packages.git
 DEBUG gpm::gpm::git              > package archive found in refspec refs/tags/[redacted]/0.1.15
 DEBUG gpm::gpm::git              > package last modified by commit Commit { id: 8a4da8237a8a1f4e89b314eaa2a02d2ee8959498, summary: "Move into package folder" }
    Found:
      [redacted].tar.gz
    in:
      ssh://github.com/[redacted]/packages.git
    at refspec:
      refs/tags/[redacted]/0.1.15
    tagged as:
      [redacted]/0.1.15
 INFO  gpm::gpm::command::install > revision PackageVersion { raw: "", version_req: None, latest: true } found as refspec refs/tags/[redacted]/0.1.15 in repository ssh://github.com/[redacted]/packages.git
 DEBUG gpm::gpm::command::install > move repository HEAD to refs/tags/[redacted]/0.1.15
 DEBUG gitlfs::lfs                > attempting to match /Users/[redacted]/.gpm/cache/35946be75ac90e769669021ee8d82335d6f5f9d88bad5e8496f35cb487fe8db4/[redacted]/[redacted].tar.gz as an LFS link
 DEBUG gitlfs::lfs                > file is an LFS link, reading LFS data
 DEBUG gitlfs::lfs                > oid = 696bc664f74d7bf4fe1bd0a899a9b8e4a739b64a240f801e4f96bc75cd401b15, size = 545436
[2/3] Downloading package
 INFO  gpm::gpm::command::install > start downloading archive [redacted].tar.gz from LFS
 DEBUG gitlfs::lfs                > attempting to match /Users/[redacted]/.gpm/cache/35946be75ac90e769669021ee8d82335d6f5f9d88bad5e8496f35cb487fe8db4/[redacted]/[redacted].tar.gz as an LFS link
 DEBUG gitlfs::lfs                > file is an LFS link, reading LFS data
 DEBUG gitlfs::lfs                > oid = 696bc664f74d7bf4fe1bd0a899a9b8e4a739b64a240f801e4f96bc75cd401b15, size = 545436
 DEBUG gitlfs::lfs                > guessing LFS server URL from ssh://github.com/[redacted]/packages.git
 DEBUG gitlfs::lfs                > guessed LFS server URL is https://github.com/[redacted]/packages.git/info/lfs
 DEBUG gitlfs::lfs                > attempting LFS download without further authentication
 TRACE gitlfs::lfs                > sending LFS object batch payload to https://github.com/[redacted]/packages.git/info/lfs/objects/batch:
{
  "operation": "download",
  "transfers": [
    "basic"
  ],
  "objects": [
    {
      "oid": "696bc664f74d7bf4fe1bd0a899a9b8e4a739b64a240f801e4f96bc75cd401b15",
      "size": 545436
    }
  ],
  "ref": {
    "name": "refs/tags/[redacted]/0.1.15"
  }
}
 DEBUG gitlfs::lfs                > unauthorized LFS download failed: {"message":"Requires authentication","documentation_url":"https://github.com/contact"}
 DEBUG gitlfs::lfs                > retrying with authentication
 WARN  gpm::gpm::ssh              > could not read the GPM_SSH_KEY environment variable: environment variable not found
 WARN  gpm::gpm::ssh              > Unable to get SSH key from ~/.ssh/config: IO error
 DEBUG gpm::gpm::ssh              > authenticate with private key located in "/Users/[redacted]/.ssh/id_rsa"
 DEBUG gitlfs::lfs                > attempting to fetch Git LFS auth token from github.com:22
 DEBUG gitlfs::lfs                > connecting to github.com:22
 DEBUG gitlfs::lfs                > SSH session handshake
 DEBUG gitlfs::lfs                > attempting SSH public key authentication with key "/Users/[redacted]/.ssh/id_rsa"
 DEBUG gitlfs::lfs                > SSH session authenticated
 DEBUG gitlfs::lfs                > execute "git-lfs-authenticate [redacted]/packages.git download" command over SSH
 DEBUG gitlfs::lfs                > {
  "href": "https://lfs.github.com/[redacted]/packages",
  "header": {
    "Authorization": "RemoteAuth gitauth-v1-gZH-mmiVlRDHQ7QJNx47ZVT9gYzHSh2iygEw1h1pSYMWdIHw5ZLOX5DNx4KmbWVtYmVyt3VzZXI6ODc0NDcyOmpvaG5tb3JyZWxspXByb3Rvo3NzaA"
  },
  "expires_at": "2020-10-22T00:09:43Z",
  "expires_in": 599
}
 TRACE gitlfs::lfs                > sending LFS object batch payload to https://lfs.github.com/[redacted]/packages/objects/batch:
{
  "operation": "download",
  "transfers": [
    "basic"
  ],
  "objects": [
    {
      "oid": "696bc664f74d7bf4fe1bd0a899a9b8e4a739b64a240f801e4f96bc75cd401b15",
      "size": 545436
    }
  ],
  "ref": {
    "name": "refs/tags/[redacted]/0.1.15"
  }
}
 ERROR gpm                        > GPM command error: Git LFS error
 ERROR gpm                        > caused by: LFS server error 403 Forbidden: 
Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.
```

**Comment by JMLX42** [comment] 2020-10-23 09:12
I just tried running `gpm install` with a public Github repo:

```bash
gpm install ssh://git@github.com/aerys/gpm-packages.git\#gpm-linux64=0.14.1 --prefix /tmp --force
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/gpm install 'ssh://git@github.com/aerys/gpm-packages.git#gpm-linux64=0.14.1' --prefix /tmp --force`
Installing package gpm-linux64=0.14.1
[1/3] Resolving package
Enter passphrase for key "XXX": 
  Found:
    gpm-linux64.tar.gz
  in:
    ssh://git@github.com/aerys/gpm-packages.git
  at refspec:
    refs/tags/gpm-linux64/0.14.1
  tagged as:
    gpm-linux64/0.14.1

    GPM (gpm) 0.14.1 changelog
    
    Summary
    
    • 0 breaking new feature
    • 0 breaking fix
    • 0 new feature
    • 1 fix
    
    Changes
    
    Fixes
    
    • 67 - Duplicated value for the Authorization HTTP header returned by /objects/batch

[2/3] Downloading package
  [00:00:04] [##############################] 2.47MB/2.47MB (0s)
[3/3] Extracting package in "/tmp"
  [00:00:00] Archive decompressed
  [00:00:00] 1/1 extracted file(s)
Done!
```

And I could not reproduce the issue.

Is the repository you're using a private repository?

**Comment by johnmorrell** [comment] 2020-10-23 09:19
Thanks for investigating. Yes, our packages are in a private repo.

**Comment by JMLX42** [comment] 2020-10-23 09:22
Please test the following branch and let me know how it works for you:

https://github.com/aerys/gpm/tree/73-failing-install-download-requiring-user-agent

**Comment by johnmorrell** [comment] 2020-10-23 10:34
That works great - thanks!

**Comment by johnmorrell** [comment] 2020-10-23 12:54
I also notice a small issue in docs I think:

```
mkdir -p ~/.gpm/sources.list
echo "ssh://path.to/my/package-repository.git" >> ~/.gpm/sources.list
```

should be:

```
mkdir -p ~/.gpm
echo "ssh://path.to/my/package-repository.git" >> ~/.gpm/sources.list
```

**Comment by JMLX42** [comment] 2020-10-26 11:15
> I also notice a small issue in docs I think:

@johnmorrell thank you. Could you please open a separate issue to track this other problem?

**Comment by JMLX42** [comment] 2020-10-26 11:29
The patch has been merged and the CI is running right now. The 0.15.0 release will be available in a few minutes:

https://github.com/aerys/gpm-packages/releases

**Closed as completed by JMLX42** 2020-10-26 11:29 UTC
Labels: bug
